name: Edmonton Radio Theatre
favicon: null
layout_spectrum: 0.11897061159834266
typography_spectrum: 0.9218273861333728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3385099738370627
  lightness: 0.4262099675834179
  saturation: 0.6323159539606422
  rhythmicContrast: 0.6477984553202987
purpose: []
